# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c896ed2eb5952ad5443e37787a5e0e250cf1a14885bdcb7a52568d3566b1e4e77abb00d3ea08ed362d311683e31ee7f2f699e5f8da8fc21a25fbd1d4e695a221

test:
  secret_key_base: e2d6dd992ace279faa9fb212f6b561e833dfa3efed5bb2eaa75dbda150bc9c117e14401b1dca56fff220d5f5eda18917785d327fcb7da4f2096df37337116549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
